# Generated by Django 5.1.4 on 2025-02-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvilla', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstock',
            name='name',
        ),
        migrations.AddField(
            model_name='newstock',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newstock',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
