# Generated by Django 5.1.3 on 2025-02-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvilla', '0004_addstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstock',
            name='mileage',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
