# Generated by Django 5.1.3 on 2025-02-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvilla', '0007_alter_addstock_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image11', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image12', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='carvilla.addstock')),
            ],
        ),
    ]
