# Generated by Django 5.1.3 on 2025-02-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvilla', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
